const data = {
  products: [
    {
      name: 'Nintendo 64',
      slug: 'nintendo-64',
      category: 'Gamming',
      image: '/images/p1.jpg', //679px x 829px
      price: 235,
      countInStock: 10,
      brand: 'Nintendo',
      rating: 9.4,
      numReviews: 10,
      description: 'high quality gaming',
    },
    {
      name: 'Playstation 1',
      slug: 'playstation-1',
      category: 'Gamming',
      image: '/images/p2.jpg',
      price: 210,
      countInStock: 10,
      brand: 'Playstation',
      rating: 6.1,
      numReviews: 10,
      description: 'high quality gaming',
    },
    {
      name: 'Gameboy Color',
      slug: 'gameboy-color',
      category: 'Gamming',
      image: '/images/p3.jpg',
      price: '180',
      countInStock: 10,
      brand: 'Nintendo',
      rating: 6.2,
      numReviews: 10,
      description: 'high quality gaming',
    },
    {
      name: 'Sega Genesis',
      slug: 'sega-genesis',
      category: 'Gamming',
      image: '/images/p4.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Sega',
      rating: 6.0,
      numReviews: 10,
      description: 'high quality gaming',
    },
    {
      name: 'Charizard',
      slug: 'charizard',
      category: 'Pokemon-Cards',
      image: '/images/p5.jpg',
      price: 1000,
      countInStock: 10,
      brand: 'Pokemon',
      rating: 10.0,
      numReviews: 10,
      description: 'high quality card gaming',
    },
    {
      name: ' Hitmonlee',
      slug: 'hitmonlee',
      category: 'Pokemon-Cards',
      image: '/images/p6.jpg',
      price: 180,
      countInStock: 10,
      brand: 'Pokemon',
      rating: 8.4,
      numReviews: 10,
      description: 'high quality card gaming',
    },
    {
      name: 'Golduck',
      slug: 'golduck',
      category: 'Pokemon-Cards',
      image: '/images/p7.jpg',
      price: 188,
      countInStock: 10,
      brand: 'Pokemon',
      rating: 8.7,
      numReviews: 10,
      description: 'high quality card gaming',
    },
    {
      name: 'Gyarados',
      slug: 'gyarados',
      category: 'Pokemon-Cards',
      image: '/images/p8.jpg',
      price: 560,
      countInStock: 10,
      brand: 'Pokemon',
      rating: 8.8,
      numReviews: 10,
      description: 'high quality card gaming',
    },
    {
      name: 'TMNT',
      slug: 'tmnt',
      category: 'Action-Figures',
      image: '/images/p9.jpg',
      price: 50,
      countInStock: 10,
      brand: 'Toys',
      rating: 7.4,
      numReviews: 10,
      description: 'high quality toy gaming',
    },
    {
      name: 'Dinosaurs',
      slug: 'dinoaurs',
      category: 'Action-Figures',
      image: '/images/p10.jpg',
      price: 18,
      countInStock: 10,
      brand: 'Toys',
      rating: 7.8,
      numReviews: 10,
      description: 'high quality toy gaming',
    },
    {
      name: 'Power Ranger',
      slug: 'power-ranger',
      category: 'Action-Figures',
      image: '/images/p11.jpg',
      price: 29,
      countInStock: 10,
      brand: 'Toys',
      rating: 6.1,
      numReviews: 10,
      description: 'high quality toy gaming',
    },
    {
      name: 'Toy Story',
      slug: 'toy-story',
      category: 'Action-Figures',
      image: '/images/p12.jpg',
      price: 16,
      countInStock: 10,
      brand: 'Toys',
      rating: 9.8,
      numReviews: 10,
      description: 'high quality toy gaming',
    },
  ],
};

export default data;
